[General]
avatarOrientation=Right
avatarScale=1
avatarShape=Cookie 4-Sided
avatarStyle=Neon Glow
avatarTintIntensity=0.35
avatarTintMode=None
avatarVisible=true
boxStyle=Split Badge
cardBorderEnabled=false
clockBorderEnabled=false
clockCardEnabled=false
clockCardOpacity=0.35
clockGridPos=0
clockScale=1
clockStyle=Editorial Typographic
colorScheme=Dynamic
currentM3Shape=16
glassBlurEnabled=true
glassBlurRadius=60
is12Hour=true
key0=83
key1=68
key2=75
key3=76
laneCount=4
loginCardEnabled=false
loginCardOpacity=0.4
loginGridPos=8
loginScale=1.005859872611465
loginStyle=Modern Glass
noteDensity=0.7
noteSpeed=0.6
preset=1
schemeFlavour=Default
schemeVariant=Tonal Spot
showLavaBlobs=true
uiFontFamily=Pixelify Sans
unlockAnimStyle=Split Horizontal
